name: Build and Push Go Docker Image to GCP

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: operator
  REGION: us-central2
  REPO_NAME: operator-tutorial

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build Go binary
      run: |
        go mod tidy
        go build -o app .

    - name: Set up Docker
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > /tmp/key.json
        gcloud auth activate-service-account --key-file=/tmp/key.json
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest .

    - name: Push Docker image
      run: |
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
